Implement regression
Balacoumarane/TabularModule pull request #14
Opened 2023-02-09 01:57 UTC by reubenlee3

2023-02-09 16:36 UTC, Balacoumarane requested changes
@reubenlee3, Thank you for the work . Is it possible to make the changes requested and submit?
After the PR is merged. We can catch-up to implement some attributes in the model

2023-02-09 16:36 UTC, Balacoumarane commented on executor.py
> -                              search_algorithm='tpe', search_metric='F1', early_stopping=True,
@reubenlee3, Shall we parametrize search metric in the respective config file as well?

2023-02-09 16:36 UTC, Balacoumarane commented on tabular_src/data/data_loader.py
> +            print(n_features)
@reubenlee3, Can you remove the print statement?

2023-02-09 16:36 UTC, Balacoumarane commented on tabular_src/feature/feature_selection.py
> -            feature_columns = list(get_config('X_train_transformed').columns)
@reubenlee3 , If possible can you upgrade pycaret to the version `3.0.0rc5`

2023-02-10 03:47 UTC, reubenlee3 commented
Hey @Balacoumarane - i've made the changes here. 

Realised i missed some parts on the evaluation, this one WIP

2023-02-11 03:25 UTC, Balacoumarane approved these changes
@reubenlee3 , Thanks for the changes. Let me merge and try to run this.

2023-02-11 03:25 UTC, merged

2023-02-12 12:20 UTC, Balacoumarane commented
@reubenlee3, I merged the codes.  I modified the regression codes to accept monotonic constrains and fixed blending & stacking for regression. Please update to the latest main branch.

In the Next PRs please complete the 
1. Evaluation
2. Scoring 
3. Feature importance(SHAP).
Please use the same code template(classification) for evaluation & feature importance. 

Thanks 😊😊